In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

df  = pd.DataFrame({'Salary':[25000,48000,71000,85000,90000,55000],
                    'City':['Bengaluru', 'Delhi', 'Hyderabad','Bengaluru','Hyderabad','Bengaluru'],
                    'Gender':['Male', 'Female', 'Female', 'Female', 'Male', 'Male'],
                    'Exp':[1,3,5,6,9,None]})
df

   Salary       City  Gender  Exp
0   25000  Bengaluru    Male  1.0
1   48000      Delhi  Female  3.0
2   71000  Hyderabad  Female  5.0
3   85000  Bengaluru  Female  6.0
4   90000  Hyderabad    Male  9.0
5   55000  Bengaluru    Male  NaN

# Encoder and Imputers

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
lab_enc = LabelEncoder()

In [5]:
df2 = lab_enc.fit_transform(df['City'])
pd.Series(df2)

0    0
1    1
2    2
3    0
4    2
5    0
dtype: int32

In [6]:
df['City'] = df2
df

   Salary  City  Gender  Exp
0   25000     0    Male  1.0
1   48000     1  Female  3.0
2   71000     2  Female  5.0
3   85000     0  Female  6.0
4   90000     2    Male  9.0
5   55000     0    Male  NaN

In [7]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer

In [8]:
ohe = OneHotEncoder()
si = SimpleImputer()

In [9]:
import pandas as pd
df = pd.DataFrame({'Salary' :[25000,48000,71000,85000,90000,55000],
                   'City' :['Bengaluru', 'delhi', 'Hyderabad', 'Bengaluru', 'Hyderabad', 'Bengaluru'],
                   'Gender' :['Male','Female','Female','Female','Male','Male'],
                   'Exp' :[1,3,5,6,9,None]})
df

   Salary       City  Gender  Exp
0   25000  Bengaluru    Male  1.0
1   48000      delhi  Female  3.0
2   71000  Hyderabad  Female  5.0
3   85000  Bengaluru  Female  6.0
4   90000  Hyderabad    Male  9.0
5   55000  Bengaluru    Male  NaN

In [10]:
ct = make_column_transformer(
    (ohe,['City', 'Gender']),
    (si, ['Exp']),
    remainder = 'passthrough')  # 'passthrough' to keep all other columns

In [11]:
encoded = pd.DataFrame(ct.fit_transform(df))
encoded

     0    1    2    3    4    5        6
0  1.0  0.0  0.0  0.0  1.0  1.0  25000.0
1  0.0  0.0  1.0  1.0  0.0  3.0  48000.0
2  0.0  1.0  0.0  1.0  0.0  5.0  71000.0
3  1.0  0.0  0.0  1.0  0.0  6.0  85000.0
4  0.0  1.0  0.0  0.0  1.0  9.0  90000.0
5  1.0  0.0  0.0  0.0  1.0  4.8  55000.0

In [12]:
# Rename the column as per your choice.
encoded = pd.DataFrame(ct.fit_transform(df),columns=['City_Bengaluru','City_delhi','City_Hyd','Gender_Female','Gender_Male','Exp','Salary'])
encoded

,City_Bengaluru,City_delhi,City_Hyd,Gender_Female,Gender_Male,Exp,Salary
0,1.0,0.0,0.0,0.0,1.0,1.0,25000.0
1,0.0,0.0,1.0,1.0,0.0,3.0,48000.0
2,0.0,1.0,0.0,1.0,0.0,5.0,71000.0
3,1.0,0.0,0.0,1.0,0.0,6.0,85000.0
4,0.0,1.0,0.0,0.0,1.0,9.0,90000.0
5,1.0,0.0,0.0,0.0,1.0,4.8,55000.0

In [13]:
# Original Data set
df

   Salary       City  Gender  Exp
0   25000  Bengaluru    Male  1.0
1   48000      delhi  Female  3.0
2   71000  Hyderabad  Female  5.0
3   85000  Bengaluru  Female  6.0
4   90000  Hyderabad    Male  9.0
5   55000  Bengaluru    Male  NaN

# get_dummies

In [14]:
df1 = pd.get_dummies(df[['City', 'Gender']])
df1

   City_Bengaluru  City_Hyderabad  City_delhi  Gender_Female  Gender_Male
0            True           False       False          False         True
1           False           False        True           True        False
2           False            True       False           True        False
3            True           False       False           True        False
4           False            True       False          False         True
5            True           False       False          False         True

In [15]:
df1 = pd.get_dummies(df[['City', 'Gender']],drop_first=True)
df1

   City_Hyderabad  City_delhi  Gender_Male
0           False       False         True
1           False        True        False
2            True       False        False
3           False       False        False
4            True       False         True
5           False       False         True

# Ordinal Encoder

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
import pandas as pd

Employee = pd.DataFrame({'Position':['SE','Manager','Team Lead','SSE'],
                         'Project':['A','B','C','D'],
                         'Salary':[25000,85000,71000,48000]})
Employee

    Position Project  Salary
0         SE       A   25000
1    Manager       B   85000
2  Team Lead       C   71000
3        SSE       D   48000

In [18]:
ord_enc = OrdinalEncoder(categories=[['SE','SSE','Team Lead','Manager'],['A','B','C','D']])
Encoded_df = ord_enc.fit_transform(Employee[['Position','Project']])
Encoded_df

array([[0., 0.],
       [3., 1.],
       [2., 2.],
       [1., 3.]])

# Binary Encoder

In [19]:
import pandas as pd

df = pd.DataFrame({'Cat_data':['A','B','C','D','E','F','G','H','I','A','A','D']})
df

   Cat_data
0         A
1         B
2         C
3         D
4         E
5         F
6         G
7         H
8         I
9         A
10        A
11        D

In [24]:
!pip install category_encoders    # install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.3-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: numpy>=1.14.0 in d:\anaconda\lib\site-packages (from category_encoders) (1.26.4)
Requirement already satisfied: scikit-learn>=0.20.0 in d:\anaconda\lib\site-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in d:\anaconda\lib\site-packages (from category_encoders) (1.11.4)
Requirement already satisfied: statsmodels>=0.9.0 in d:\anaconda\lib\site-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in d:\anaconda\lib\site-packages (from category_encoders) (2.1.4)
Requirement already satisfied: patsy>=0.5.1 in d:\anaconda\lib\site-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\anaconda\lib\site-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in d:\anaconda\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in d:\anaconda\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\anaconda\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.2.0)
Requirement already satisfied: packaging>=21.3 in d:\anaconda\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (23.1)
Downloading category_encoders-2.6.3-py2.py3-none-any.whl (81 kB)
   ---------------------------------------- 0.0/81.9 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/81.9 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/81.9 kB ? eta -:--:--
   --------------- ------------------------ 30.7/81.9 kB 187.9 kB/s eta 0:00:01
   -------------------- ------------------- 41.0/81.9 kB 178.6 kB/s eta 0:00:01
   -------------------- ------------------- 41.0/81.9 kB 178.6 kB/s eta 0:00:01
   -------------------- ------------------- 41.0/81.9 kB 178.6 kB/s eta 0:00:01
   -------------------- ------------------- 41.0/81.9 kB 178.6 kB/s eta 0:00:01
   -------------------- ------------------- 41.0/81.9 kB 178.6 kB/s eta 0:00:01
   -------------------- ------------------- 41.0/81.9 kB 178.6 kB/s eta 0:00:01
   ---------------------------------------- 81.9/81.9 kB 169.7 kB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.3

In [27]:
from category_encoders import BinaryEncoder
from sklearn.preprocessing import OneHotEncoder

In [28]:
bi_enc = BinaryEncoder()

1. Count the number of categories(except duplicate)
2. A-1, B-2,C-3 and so on.
3. Open calculator in programmer mode and click number 1 and check Binary,2 for B and check the binary

In [29]:
df_bi = bi_enc.fit_transform(df)
df_bi

    Cat_data_0  Cat_data_1  Cat_data_2  Cat_data_3
0            0           0           0           1
1            0           0           1           0
2            0           0           1           1
3            0           1           0           0
4            0           1           0           1
5            0           1           1           0
6            0           1           1           1
7            1           0           0           0
8            1           0           0           1
9            0           0           0           1
10           0           0           0           1
11           0           1           0           0

# Comparing with OneHotEncoder

In [30]:
ohe = OneHotEncoder(sparse=False)
ohe.fit_transform(df[['Cat_data']])

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.]])

# KNN Imputer

In [31]:
df = pd.DataFrame({'Salary':[25000,48000,71000,85000,90000,49000],
                   'City':['Bengaluru','Delhi','Hyderabad','Bengaluru','Hyderabad','Bengaluru'],
                   'Gender':['Male','Female','Female','Female','Male','Male'],
                   'Exp':[1,3,5,6,9,None]})
df

   Salary       City  Gender  Exp
0   25000  Bengaluru    Male  1.0
1   48000      Delhi  Female  3.0
2   71000  Hyderabad  Female  5.0
3   85000  Bengaluru  Female  6.0
4   90000  Hyderabad    Male  9.0
5   49000  Bengaluru    Male  NaN

In [ ]:
# KNN imputer will try to find the relation with other columns and impute the data according the relation with other columns.
# In this case Exp NaN is depending on the similarity with Fare columns.

In [32]:
from sklearn.impute import KNNImputer

In [33]:
knnimp = KNNImputer(n_neighbors=2)
knn_imp = pd.DataFrame(knnimp.fit_transform(df[['Salary','Exp']]))
knn_imp

         0    1
0  25000.0  1.0
1  48000.0  3.0
2  71000.0  5.0
3  85000.0  6.0
4  90000.0  9.0
5  49000.0  4.0

# Iterative Imputer

This method treat other columns (which does not have nulls as feature and train on them and treat null column as
label. Finally it will predict the NaN data and impute. It's just like regression problem.Here null column is label.

In [34]:
# before using Iterative Imputer , We need to enable it using below code
from sklearn.experimental import enable_iterative_imputer


# import Iterative imputer
from sklearn.impute import IterativeImputer

In [35]:
df = pd.DataFrame({'Salary':[25000,48000,71000,85000,90000,55000],
                   'City':['Bengaluru','Delhi','Hyderabad','Bengaluru','Hyderabad','Bengaluru'],
                   'Gender':['Male','Female','Female','Female','Male','Male'],
                   'Exp':[1,3,5,6,9,None]})
df

   Salary       City  Gender  Exp
0   25000  Bengaluru    Male  1.0
1   48000      Delhi  Female  3.0
2   71000  Hyderabad  Female  5.0
3   85000  Bengaluru  Female  6.0
4   90000  Hyderabad    Male  9.0
5   55000  Bengaluru    Male  NaN

In [36]:
iter_impute = IterativeImputer()
ite_imp= pd.DataFrame(iter_impute.fit_transform(df[['Salary','Exp']]),columns=['Salary','Exp'])
ite_imp

    Salary       Exp
0  25000.0  1.000000
1  48000.0  3.000000
2  71000.0  5.000000
3  85000.0  6.000000
4  90000.0  9.000000
5  55000.0  3.864759